#{% set data = load_setup_py_data() %} # do not remove this line
# {% set data = load_file_data('pyproject.toml') %}
# {% set proj = data['project'] %}
# {% set urls = data['project']['urls'] %}

context:
  version: ${{ load_from_file('pyproject.toml').project.version }}
  home: ${{ load_from_file('pyproject.toml').project.urls.Homepage }}
  summary: ${{ load_from_file('pyproject.toml').project.description }}
  dev_url: ${{ load_from_file('pyproject.toml').project.urls.Repository }}
  doc_url: ${{ load_from_file('pyproject.toml').project.urls.Documentation }}

package:
  name: "mokit"
  version: ${{ version }}

source:
  - git: https://gitlab.com/jxzou/mokit
    rev: 9769e2264f0671ff84fd42183c38ab8f324d26f6
    #branch: "master"


build:
  number: 3
  # string: "py{{ PY_VER }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  files:
    exclude:
      - "**/__pycache__"

requirements:
  build:
    - if: unix
      then: make
    - if: win
      then: make
    - ${{ compiler('fortran') }}
    - python 
    - pip
    #- setuptools <=73
    - numpy 
    #- blas=*=*openblas
    - openblas 
    # - libgfortran5
    - if: osx
      then: llvm-openmp
    # - sysroot_linux-64 2.17
  host:
    - python
    - pip
    - numpy
    - openblas
    - if: osx
      then: llvm-openmp
  run:
    - python
    - numpy 
    # - libgfortran5
    # - libgomp

about:
  homepage:            ${{ home }}
  license:         "Apache-2.0"
  summary:         ${{ summary }}
  description:     "MOKIT offers various utilities and modules to transfer MOs among various quantum chemistry software packages.\nBesides, the automr program in MOKIT can set up and run common multi-reference calculations in a black-box way."
  repository:         ${{ dev_url }}
  documentation:         ${{ doc_url }}
