#{% set data = load_setup_py_data() %} # do not remove this line
# {% set data = load_file_data('pyproject.toml') %}
# {% set proj = data['project'] %}
# {% set urls = data['project']['urls'] %}

context:
  version: ${{ load_from_file('pyproject.toml').project.version }}
  home: ${{ load_from_file('pyproject.toml').project.urls.Homepage }}
  summary: ${{ load_from_file('pyproject.toml').project.description }}
  dev_url: ${{ load_from_file('pyproject.toml').project.urls.Repository }}
  doc_url: ${{ load_from_file('pyproject.toml').project.urls.Documentation }}

package:
  name: "mokit"
  version: ${{ version }}

source:
  - git: https://gitlab.com/jxzou/mokit
    rev: c62fa039f911eb24f14043400aea8906d25f6924
    #branch: "master"

build:
  number: 101
  # string: "py{{ PY_VER }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  files:
    exclude:
      - "**/__pycache__"
      - "**/*.pyc"

requirements:
  build:
    - make
    - ${{ compiler('fortran') }}
    - gcc_win-64
    - python
    - setuptools <=73
    - meson
    - ninja
    - pip
    - numpy 2.4.*
    - blas * *openblas
    - openblas
  host:
    - python
    - pip
    - numpy 2.4.*
    - blas * *openblas
    - openblas
  run:
    - python
    - numpy >=2.4
    - openblas

about:
  homepage:            ${{ home }}
  license:         "Apache-2.0"
  summary:         ${{ summary }}
  description:     "MOKIT offers various utilities and modules to transfer MOs among various quantum chemistry software packages.\nBesides, the automr program in MOKIT can set up and run common multi-reference calculations in a black-box way."
  repository:         ${{ dev_url }}
  documentation:         ${{ doc_url }}
